### ISSUE TITLE
Local development setup

### ISSUE THREAD

**Issue by vishnubhadri** [DulLabs/bhai-lang#174]
### Description

Please provide some documentation for local setup (windows, linux and mac). i tried setup in local machine but i am facing below error in windows machine
```
D:\Github\bhai-lang>npm run dev
 bhai-lang@0.0.1 dev D:\Vish\Github\bhai-lang
 turbo run dev --parallel
 Packages in scope: bhai-lang-docs, bhai-lang-interpreter, bhai-lang-parser, bhailang, config, tsconfig
 Running dev in 6 packages
bhai-lang-interpreter:dev: cache miss, executing 2a556ffa52b64e14
bhai-lang-parser:dev: cache miss, executing 27346a7de9bdad96
bhai-lang-docs:dev: cache miss, executing 9251030e0e6ed19c
bhailang:dev: cache miss, executing 25090cfb1fe6f5d5
bhai-lang-docs:dev:
bhai-lang-docs:dev: > bhai-lang-docs@0.0.1 dev D:\Vish\Github\bhai-lang\apps\docs
bhai-lang-docs:dev: > TAILWIND_MODE=watch next dev
bhai-lang-docs:dev:
bhai-lang-interpreter:dev:
bhai-lang-interpreter:dev: > bhai-lang-interpreter@0.0.1 dev D:\Vish\Github\bhai-lang\packages\interpreter
bhai-lang-interpreter:dev: > ts-node src/index.ts
bhai-lang-interpreter:dev:
bhailang:dev:
bhailang:dev: > bhailang@0.0.7 dev D:\Vish\Github\bhai-lang\packages\cli
bhailang:dev: > node --loader ts-node/esm
bhailang:dev:
bhai-lang-docs:dev: 'TAILWIND_MODE' is not recognized as an internal or external command,
bhai-lang-docs:dev: operable program or batch file.
bhai-lang-parser:dev:
bhai-lang-parser:dev: > bhai-lang-parser@0.0.1 dev D:\Vish\Github\bhai-lang\packages\parser
bhai-lang-parser:dev: > ts-node src/index.ts
bhai-lang-parser:dev:
bhai-lang-docs:dev: npm ERR! code ELIFECYCLE
bhai-lang-docs:dev: npm ERR! errno 1
bhai-lang-docs:dev: npm ERR! bhai-lang-docs@0.0.1 dev: `TAILWIND_MODE=watch next dev`
bhai-lang-docs:dev: npm ERR! Exit status 1
bhai-lang-docs:dev: npm ERR!
bhai-lang-docs:dev: npm ERR! Failed at the bhai-lang-docs@0.0.1 dev script.
bhai-lang-docs:dev: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
bhai-lang-docs:dev: npm WARN Local package.json exists, but node_modules missing, did you mean to install?
bhai-lang-docs:dev:
bhai-lang-docs:dev: npm ERR! A complete log of this run can be found in:
bhai-lang-docs:dev: npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2022-03-15T19_03_58_814Z-debug.log
bhai-lang-docs:dev: Error: command finished with error: command (apps\docs) npm run dev exited (1)
bhai-lang-parser:dev: C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:820
bhai-lang-parser:dev:     return new TSError(diagnosticText, diagnosticCodes);
bhai-lang-parser:dev:            ^
bhai-lang-parser:dev: TSError: ⨯ Unable to compile TypeScript:
bhai-lang-parser:dev: error TS6053: File 'tsconfig/base.json' not found.
bhai-lang-parser:dev:
bhai-lang-parser:dev:     at createTSError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:820:12)
bhai-lang-parser:dev:     at reportTSError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:824:19)
bhai-lang-parser:dev:     at createFromPreloadedConfig (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:835:36)
bhai-lang-parser:dev:     at phase4 (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:469:44)
bhai-lang-parser:dev:     at bootstrap (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:85:10)
bhai-lang-parser:dev:     at main (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:54:10)
bhai-lang-parser:dev:     at Object.<anonymous> (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:717:3)
bhai-lang-parser:dev:     at Module._compile (internal/modules/cjs/loader.js:999:30)
bhai-lang-parser:dev:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
bhai-lang-parser:dev:     at Module.load (internal/modules/cjs/loader.js:863:32) {
bhai-lang-parser:dev:   diagnosticCodes: [ 6053 ]
bhai-lang-parser:dev: }
bhai-lang-interpreter:dev: C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:820
bhai-lang-interpreter:dev:     return new TSError(diagnosticText, diagnosticCodes);
bhai-lang-interpreter:dev:            ^
bhai-lang-interpreter:dev: TSError: ⨯ Unable to compile TypeScript:
bhai-lang-interpreter:dev: error TS6053: File 'tsconfig/base.json' not found.
bhai-lang-interpreter:dev:
bhai-lang-interpreter:dev:     at createTSError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:820:12)
bhai-lang-interpreter:dev:     at reportTSError (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:824:19)
bhai-lang-interpreter:dev:     at createFromPreloadedConfig (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:835:36)
bhai-lang-interpreter:dev:     at phase4 (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:469:44)
bhai-lang-interpreter:dev:     at bootstrap (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:85:10)
bhai-lang-interpreter:dev:     at main (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:54:10)
bhai-lang-interpreter:dev:     at Object.<anonymous> (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:717:3)
bhai-lang-interpreter:dev:     at Module._compile (internal/modules/cjs/loader.js:999:30)
bhai-lang-interpreter:dev:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
bhai-lang-interpreter:dev:     at Module.load (internal/modules/cjs/loader.js:863:32) {
bhai-lang-interpreter:dev:   diagnosticCodes: [ 6053 ]
bhai-lang-interpreter:dev: }
bhai-lang-parser:dev: npm ERR! code ELIFECYCLE
bhai-lang-parser:dev: npm ERR! errno 1
bhai-lang-interpreter:dev: npm ERR! code ELIFECYCLE
bhai-lang-interpreter:dev: npm ERR! errno 1
bhai-lang-parser:dev: npm ERR! bhai-lang-parser@0.0.1 dev: `ts-node src/index.ts`
bhai-lang-parser:dev: npm ERR! Exit status 1
bhai-lang-parser:dev: npm ERR!
bhai-lang-parser:dev: npm ERR! Failed at the bhai-lang-parser@0.0.1 dev script.
bhai-lang-parser:dev: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
bhai-lang-interpreter:dev: npm ERR! bhai-lang-interpreter@0.0.1 dev: `ts-node src/index.ts`
bhai-lang-interpreter:dev: npm ERR! Exit status 1
bhai-lang-interpreter:dev: npm ERR!
bhai-lang-interpreter:dev: npm ERR! Failed at the bhai-lang-interpreter@0.0.1 dev script.
bhai-lang-interpreter:dev: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
bhai-lang-parser:dev: npm WARN Local package.json exists, but node_modules missing, did you mean to install?
bhai-lang-parser:dev:
bhai-lang-parser:dev: npm ERR! A complete log of this run can be found in:
bhai-lang-parser:dev: npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2022-03-15T19_03_59_156Z-debug.log
bhai-lang-interpreter:dev: npm WARN Local package.json exists, but node_modules missing, did you mean to install?
bhai-lang-interpreter:dev:
bhai-lang-interpreter:dev: npm ERR! A complete log of this run can be found in:
bhai-lang-interpreter:dev: npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2022-03-15T19_03_59_171Z-debug.log
command (apps\docs) npm run dev exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    1.322s

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bhai-lang@0.0.1 dev: `turbo run dev --parallel`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bhai-lang@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2022-03-15T19_03_59_203Z-debug.log

```

### Domain

Bhai Lang

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) & [Code of conduct](https://github.com/DulLabs/bhai-lang/blob/develop/README.md) of bhai-lang.

**Comment by ankitchouhan1020** [comment]
Please check https://github.com/DulLabs/bhai-lang/issues/117

We are not using window setup right now. So it is hard for us to get actual issue.
Currently it looks like some node_modules location issue or environment variable assignment issue.

#117 is open. Closing this for now.

**Comment by shankarkrupa** [comment]
Here is how I have **fixed** this temporarily in Windows:
Step 1
-------
1) Open bhai-lang\apps\docs\package.json
2) Go to the scripts block and locate the line that starts with "dev" (currently this is at line number 6 as of today)
3) Remove the portion **TAILWIND_MODE=watch**

Now try to build and run. You would be able to make changes and also play around the code and compile/run but this is not a permanent solution
